on:
   push:
     branches: [ main ]
  # pull_request:
    # branches: [ main ]

jobs:
  build-client:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [ 22.x ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Corepack enable
        run: corepack enable

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn

      - name: Run build
        run: yarn workspace @project-bootstrap/pkg-client build
